<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{% block title %}Glen Codes{% endblock %}</title>
  <link rel="stylesheet" href="/css/main.css">
  <!--
                                  :=========,
                            =~~~~~~~~~~~~~~~~~~~~~=.
                        =~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=
                     =~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=
                  :~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                :~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              .~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             =~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          =~~~~?ODO7~~~~~~~~~~~~~~~~~~~~~~~~~~~~~?ODO$=~~~~~~~~~~~~~
          ~~7MMMMMMMMM?~~~~~~~~~~~~~~~~~~~~~~~OMMMMMMMMMD=~~~~~~~~~~~.
        ,~~MMM?     DMMM?~~~~~~~~~~~~~~~~~~~NMMM=     .NMMM?~~~~~~~~~~
        ~~MM?     ,MMMMMMM~~~~~~~~~~~~~~~~+MMM       .MMMMMMO~~~~~~~~~~
       =~MMD      MMMMMMMMD~~~~~~~~~~~~~~~MM,        NMMMMMMMM~~~~~~~~~~
      =~DMD       DMMMMMMMMO~~~~~~~~~~~~~MM?         OMMMMMMMM?~~~~~~~~~=
      ~~MM.        $MMMMM=MM~~~~~~~~~~~~DMD           MMMMMM:MM~~~~~~~~~~.
     =~~MM            .   MM~~~~~~~~~~~~MM              ..   NM7~~~~~~~~~=
    .~~=MM                MM=~~~~~~~~~~~MM                   OMD~~~~~~~~~~
    =~~~MM                MM=~~~~~~~~~~~MM                   OMO~~~~~~~~~~,
    ~~~~MM                MM~~~~~~~~~~~~MM:                  MM?~~~~~~~~~~=
    ~~~~NMMMMMMMMMMMMMMMMMMM~~~~~~~~~~~~OMMMMMMMMMMMMMMMMMMMMMM~~~~~~~~~~~~
    ~~~~~???++??++??++??++?=~~~~~~~~~~~~~+++??++??++??++??++??=~~~~~~~~~~~~,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~:
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~,
    ~~~~~~===================================================~~~~~~~~~~~~~~.
    ~~~~~~MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~~~~~~~~~~~~=
    =~~~~~~~+MMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMM+~~~~~~~~~~~:
    ,~~~~~~~~MMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONMD~~~~~~~~~~~
     =~~~~~~~DMNOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONMM~~~~~~~~~~~
      ~~~~~~~~MMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMM~~~~~~~~~~.
      =~~~~~~~MMNOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMM~~~~~~~~~=
       ~~~~~~~~MMNOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMM$~~~~~~~~~
        ~~~~~~~=MMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMM~~~~~~~~~
        :~~~~~~~OMMOOOOOOOOOOOOOOOOOOOOOOO7??7OOOOOOOOOOOOOMMD~~~~~~~~
          ~~~~~~~7MMOOOOOOOOOOOOOOOOO7,:::::::::,,OOOOOOOOMMD~~~~~~~~,
          =~~~~~~~MMMOOOOOOOOOOOOOOO,::::::::::::::,OOOOONMM~~~~~~~~.
            ~~~~~~=7MMOOOOOOOOOOOO,::::::::::::::::::=OOMMN~~~~~~~~.
             =~~~~~~+MMMOOOOOOOOO,::::::::::::::::::,?MMM7~~~~~~~~
              :~~~~~~~DMMMOOOOOO,::::::::::::::::::7MMMD~~~~~~~~
                =~~~~~~~MMMMOOO?:::::::::::::::,7MMMM$~~~~~~~~,
                  =~~~~~~~OMMMMN=,:::::::,,:OMMMMMD~~~~~~~~~,
                    .=~~~~~~~=NMMMMMMMMMMMMMMMO?~~~~~~~~~=
                       .=~~~~~~~~~~~+???=~~~~~~~~~~~~~=.
                           :=~~~~~~~~~~~~~~~~~~~~~=:
                                ..:====~====:,
                                   .,,.....,
  -->
</head>
<body>
  <main role="main">
    {% block content %}{% endblock %}
  </main>
</body>
</html>
